parameters:
- name: branch
  type: string

steps:
# - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - pwsh: |
      git config user.email "azure-pipelines-bot@microsoft.com"
      git config user.name "azure-pipelines-bot"
      git checkout -f origin/$env:BRANCH_NAME
    displayName: Checkout branch
    env:
      BRANCH_NAME: ${{ parameters.branch }}
