parameters:
- name: branch
  type: string

variables:
  checkoutBranch: ${{ parameters.branch }}

steps:
# - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
  - script: |
      # git config user.email "azure-pipelines-bot@microsoft.com"
      # git config user.name "azure-pipelines-bot"

      # git checkout -f origin/${{ parameters.branch }}
      echo "Checkout branch: ${{ parameters.branch }}"
    displayName: Checkout branch
    condition: ne(variables.checkoutBranch, '')
